In [3]:
using Plots
using DifferentialEquations
include("../dynamics/lagrange.jl")

In [38]:
x,y = symbols("x y")
j = [i*x*y for i in 1:3]

3-element Array{SymEngine.Basic,1}:
   x*y
 2*x*y
 3*x*y

In [48]:
zeros(length(x), length(j))

1×3 Array{Float64,2}:
 0.0  0.0  0.0

In [64]:
function jacobian(f,x)
    m = length(f)
    n = length(x)
    
    jac = [diff(f[i],x[j]) for i in 1:m, j in 1:n]
    
    return jac
end


jacobian (generic function with 1 method)

In [68]:
jacobian(j,[x,y,y])

3×3 Array{SymEngine.Basic,2}:
   y    x    x
 2*y  2*x  2*x
 3*y  3*x  3*x

In [112]:
ddt = r -> jacobian(r, [q;dq])*[dq;ddq]
M2Q = (M,w) -> jacobian(w,dq)'*(M);


In [103]:
# Lagrange Example, pendulum

In [104]:
m,l,g, θ, dθ, ddθ = symbols("m l g θ dθ ddθ")

(m, l, g, θ, dθ, ddθ)

In [105]:
q = θ
dq = dθ
ddq = ddθ

ihat = [1;0]
jhat = [0;1]

2-element Array{Int64,1}:
 0
 1

In [106]:
r = l*sin(q)*ihat + l*cos(q)*jhat
dr = ddt(r)

println(r)
println(dr)

SymEngine.Basic[l*sin(θ), l*cos(θ)]
SymEngine.Basic[l*cos(θ)*dθ, -l*sin(θ)*dθ]


In [115]:
K = 0.5*m*dr'*dr
U = m*g*dot(r,jhat)

L = K-U

-g*l*m*cos(θ) + 0.5*l^2*m*sin(θ)^2*dθ^2 + 0.5*l^2*m*cos(θ)^2*dθ^2

In [109]:
eom = ddt(jacobian(L,dq)') - jacobian(L,q)


1×1 Array{SymEngine.Basic,2}:
 (1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - g*l*m*sin(θ)

In [110]:
A = jacobian(eom,ddq)
b = A*ddq - eom

1×1 Array{SymEngine.Basic,2}:
 (1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - ((1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - g*l*m*sin(θ))

In [111]:
println(A)
println(b)

SymEngine.Basic[1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2]
SymEngine.Basic[(1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - ((1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - g*l*m*sin(θ))]


In [120]:
eqn(θn, ddθn) = subs(eom[1],θ=>θn,ddθ=>ddθn)

eqn (generic function with 1 method)

In [121]:
eqn(1,2)

-g*l*m*sin(1) + 2*(1.0*l^2*m*sin(1)^2 + 1.0*l^2*m*cos(1)^2)