In [1]:
using Plots
using DifferentialEquations
include("../dynamics/lagrange.jl")

INFO: Recompiling stale cache file /home/luke/.julia/lib/v0.6/Showoff.ji for module Showoff.
INFO: Recompiling stale cache file /home/luke/.julia/lib/v0.6/Plots.ji for module Plots.
INFO: Recompiling stale cache file /home/luke/.julia/lib/v0.6/DiffEqNoiseProcess.ji for module DiffEqNoiseProcess.
INFO: Recompiling stale cache file /home/luke/.julia/lib/v0.6/DifferentialEquations.ji for module DifferentialEquations.


lagrange

In [2]:
x,y = symbols("x y")
j = [i*x*y for i in 1:3]

LoadError: UndefVarError: symbols not defined

In [3]:
zeros(length(x), length(j))

LoadError: UndefVarError: x not defined

In [4]:
function jacobian(f,x)
    m = length(f)
    n = length(x)
    
    jac = [diff(f[i],x[j]) for i in 1:m, j in 1:n]
    
    return jac
end


jacobian (generic function with 1 method)

In [5]:
jacobian(j,[x,y,y])

LoadError: UndefVarError: j not defined

In [6]:
ddt = r -> jacobian(r, [q;dq])*[dq;ddq]
M2Q = (M,w) -> jacobian(w,dq)'*(M);


In [7]:
# Lagrange Example, pendulum

In [8]:
m,l,g, θ, dθ, ddθ = symbols("m l g θ dθ ddθ")

LoadError: UndefVarError: symbols not defined

In [105]:
q = θ
dq = dθ
ddq = ddθ

ihat = [1;0]
jhat = [0;1]

2-element Array{Int64,1}:
 0
 1

In [106]:
r = l*sin(q)*ihat + l*cos(q)*jhat
dr = ddt(r)

println(r)
println(dr)

SymEngine.Basic[l*sin(θ), l*cos(θ)]
SymEngine.Basic[l*cos(θ)*dθ, -l*sin(θ)*dθ]


In [115]:
K = 0.5*m*dr'*dr
U = m*g*dot(r,jhat)

L = K-U

-g*l*m*cos(θ) + 0.5*l^2*m*sin(θ)^2*dθ^2 + 0.5*l^2*m*cos(θ)^2*dθ^2

In [109]:
eom = ddt(jacobian(L,dq)') - jacobian(L,q)


1×1 Array{SymEngine.Basic,2}:
 (1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - g*l*m*sin(θ)

In [110]:
A = jacobian(eom,ddq)
b = A*ddq - eom

1×1 Array{SymEngine.Basic,2}:
 (1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - ((1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - g*l*m*sin(θ))

In [111]:
println(A)
println(b)

SymEngine.Basic[1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2]
SymEngine.Basic[(1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - ((1.0*l^2*m*sin(θ)^2 + 1.0*l^2*m*cos(θ)^2)*ddθ - g*l*m*sin(θ))]


In [120]:
eqn(θn, ddθn) = subs(eom[1],θ=>θn,ddθ=>ddθn)

eqn (generic function with 1 method)

In [121]:
eqn(1,2)

-g*l*m*sin(1) + 2*(1.0*l^2*m*sin(1)^2 + 1.0*l^2*m*cos(1)^2)